name: simple_pubsub
description: A simple in-memory pubsub implementation for Dart.
version: 1.0.0
homepage: https://jaguar-dart.github.io
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
